# Generated by Django 5.1.6 on 2025-03-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fruits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='car_models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('car_description', models.TextField()),
                ('car_image', models.ImageField(upload_to='Receipe')),
            ],
        ),
    ]
